### ISSUE TITLE
Set destination folder for new note

### ISSUE THREAD

**Issue by User-is-using** [studiowebux/obsidian-spotify-link#24]
Hi,
thank you very much for developing this plugin.
I have everything set up and it works, but I am stuck on one thing.
My use case is that I listen to a podcast in Spotify and spontaneously decide that I want to have a note about it in Obsidian.
I open Obsidian and then select the option “create file for currently playing episode using template” and save the current podcast. (I have created a template and it works great).
Unfortunately, the plugin creates a new folder with the name of the note I was in before. 
This is of course a completely different one.

I would appreciate the option of selecting a fixed destination folder (or a completely new note). 
I've tried various things with the name in default destination and the toggle buttons, but the new note never ends up in the folder I want.
Is there a specific name (path) for the default destination?
I am a total beginner and have no clue how file names etc. should be named correctly. 
Maybe I have overlooked something else....

Is it also possible to be taken there directly after creating the note? 
I would like to add a comment to my note explaining why I have created a note for it. 
At the moment I am always in the note I was in before and I have to switch to the new note myself.

Many thanks in advance!!
M.

**Comment by User-is-using** [comment]
I tried a bit more and I think I have found the error.
There are other options in the command palette than the one I used:
In the note itself, there are also selection options via the three dots at the top right “more options” at the bottom and it always goes wrong here. 
Perhaps I always select the wrong command here and the plug-in does exactly what it should.... 
The name is also shorter than via the command palette.
I'll have a look at this and probably build a hotkey...
But thanks again for the plugin and the further development :-)

All the best for you
M.

**Comment by studiowebux** [comment]
Hello !

Thanks for asking !

The plugin has multiple ways to create new notes, based on what I tested, all of them automatically open the note upon creation when the `Auto Open` is set to On. 

When the note already exists and the overwrite is Off, the existing note will open, but no changes will be applied.

For creation:

1. You can right click on any existing  directory and select from one of the four options to create and automatically be redirect to the new note, and the new note will be created under the selected Directory.
2. Use a hotkey or the command palette (CMD+P), this one will create the note in the directory defined in the settings
- If the `Default destination` is unset it will put the note at the root of your vault.
- otherwise it creates the note in the defined directory.

This is the config I used when testing and before releasing new version
<img width="826" alt="image" src="https://github.com/user-attachments/assets/46e372a6-cfdd-4155-bf58-92b696379112">

Let me know if I answered your questions.

**Comment by studiowebux** [comment]
Yeah you are right ! 
There are 8 of them with the command palette, 

4 actions that create a new file following the `Default destination` (the ones that starts with `create file`)
and the 4 others are appending in the opened file

Feel free to reopen if anything
